### ISSUE TITLE
Fix transparency bugs that completely hinders gameplay

### ISSUE THREAD

**Issue by katriellucas** [katriellucas/lecarde-2#1]
## Problem
It's not possible to see Efrain when underwater, dark areas and such.

## Task
Replay the game and comment below areas with non-transparent water/dark and other effects that completely hinders gameplay, like when the player ts unable to see the character, the comment should have at least:
- Name of the area
- Screenshots of the location in the area

## Places
- [x] opening Rome: water transparency has to be increased, efrain does not appear after diving in it.
- [x] dark forest: Water transparency has to be increased, "Fish" enemies cannot be seen in water
- [x] villagers and villages: the water is not transparent in the Saint Anselme Village well.
- [x] Servigny earldom/bridge: The water is not transparent in this area making it impossible to explore underwater afterwards.
- [x] Servigny earldom/ ferryman lake: the water is not transparent here, not being able to explore underwater afterwards
- [x] La Tourvelle earldom/ Rivoire cave: no water transparency
- [x] Castle of Eternal Night/Underground Aqueduct: no water transparency
- [x] La Tourvelle castle: the spot light room should have transparency for the character to be visible. is this dark effect technically water?
- [x] Necromancer sub-boss: when starting to enter his arena, he uses red laser with transparent effect, actions cannot be seen.
- [x] Underground aqueduct: water transparency lost at near the woman who wants the rose
- [x] and near the pickup location of the mask of moon
