### ISSUE TITLE
Fix general transparency effects

### ISSUE THREAD

**Issue by katriellucas** [katriellucas/lecarde-2#6]
## Problem
Pretty much the same problem of #1, but it's not as serious.

## Task
Document here on comments all the transparency effects that doesn't hinder gameplay.

## Places
- [x] Title screen: The fog should have transparency
- [x] villagers and villages: the daytime cycle coloring of the screens will have to be corrected to the normal color
- [x] Probably several light effects and ilumination have this issue, more investigation/searching is necessary
- [x] Servigny Earldom/abandoned (Gondre) mine: no water transparency
- [x] Gondre mine: lamp lighting have to be fixed
- [x] villagers and villages/Saint Anselme: lighting correction outside and inside all houses in the village
- [x] La Tourvelle earldom/Sautelle cemetery: The tears from this enemy should be transparent
- [x] La tourvelle earldom/Forest of Isigny: a small portion of water should have transparency
- [x] enemy/skeleton gunman: gunshot should have transparency
- [x] St Justine/Count Albaret boss fight: the light should have transparency
- [x] Warp rooms: color having differences to the original
- [x] Horror Gallery: general background mirrors should have transparency
- [x] Four season hall: running water in background should have transparency
- [x] horror gallery: This room should have the skull phantom trap transparency
- [x] four season hall: after defeating nightmare plant, the glass should have some transparency
- [x] Castle garden: near the trianon entrance, the curtain should have some transparency
- [x] castle garden: near the exit to altar, water should have transparency
- [x] La tourvelle earldom/Ice cave: before and after the rope of thorns the lights have to be fixed
- [x] La tourvelle earldom/ villagers and villages: Lighting needs to be fixed
- [x] La tourvelle earldom/ villagers and villages: Lighting needs to be fixed
- [x] La tourvelle earldom/ice cave: Lighting needs to be fixed
- [x] Garden of the Dead: water running in background should have transparency
- [x] La tourvelle earldom/ice cave: after the first secret passage there is a lamp to be fixed
- [x] La tourvelle earldom/ice cave:lamps to be fixed at the top
- [x] La tourvelle earldom/ice cave: after climbing the rope there is a lamp to be fixed
- [x] enemy/hunting girl: this enemy should have periodly transparency, on her body only
- [x] La tourvelle earldom/ice cave: lamps to be fixed in the first part below
- [x] La tourvelle earldom/ice cave: lamps to be built in the second bottom part
- [x] La tourvelle earldom/ice cave: lamp to be repaired in the second secret passage
- [x] The "choose your death" room in main castle/princely rooms: this small portion of insta-death water should have transparency
- [x] Castle under gound cave: mirror warp door should have transparency
- [x] horror gallery: mirror warp door should have transparency
- [x] Garden of the dead/ paths to black armor: mirror in background should have transparency
- [x] Garden of the dead: running water in background should have transparency
- [x] Castle of eternal night/ princely rooms: mirror warp door should have transparency
- [x] main Castle/ Altar/ escape section after defeating shadows of 3 counts: running water in the background should be transparency
- [x] final room before lucifer rfight: running water in background should have transparency
- [x] La tourvelle earldom/Sautelle cemetery: lighting to be fixed in the red skeleton room
- [x] La tourvelle earldom/Sautelle cemetery: lighting to be fixed in the second room of the red skeletons
- [x] La tourvelle earldom/La tourvelle castle: lighting to be fixed in the first room where the statue is located
- [x] La tourvelle earldom/La tourvelle castle: lighting to be fixed in the second room which is the hallway
- [x] La tourvelle earldom/La tourvelle castle: lighting to be fixed in the room with the skeleton on the ceiling and statues glowing
- [x] La tourvelle earldom/La tourvelle castle: lighting to be fixed in the room above after climbing the first ladder
- [x] La tourvelle earldom/La tourvelle castle: lighting to be fixed in the room after climbing the second ladder
- [x] La tourvelle earldom/La tourvelle castle: lighting to be fixed in secret passage with ectoplasm
- [x] La tourvelle earldom/La tourvelle castle: Lighting needs to be fixed in areas with overhead spike traps
- [x] La tourvelle earldom/La tourvelle castle: lighting has to be fixed in the area where the save point is
- [x] La tourvelle earldom/La tourvelle castle: lighting has to be fixed in the area to the left of the savior, where there is the opening below
- [x] La tourvelle earldom/La tourvelle castle: lighting has to be fixed in the area where the puzzle is
- [x] Albaret Earldom/Delbasse City: the lighting that is in the window and in the doors has to be darker
- [x] Albaret Earldom/Delbasse City: lighting of the poles outside and the lamps inside the houses have to be fixed
- [x] Albaret Earldom/Delbasse City: the light that appears in the afternoon in the church has to be fixed
- [x] Albaret Earldom/St Justine: lighting has to be fixed in the first room where the statue is
- [x] Albaret Earldom/St Justine: lighting has to be fixed in the hallway
- [x] Albaret Earldom/St Justine: lighting has to be fixed in the room with ectoplasm on the right
- [x] Albaret Earldom/St Justine: lighting has to be fixed in the room where there is a giant spider and a copy of the university statue
- [x] Albaret Earldom/St Justine: lighting has to be fixed in the first upstairs room that has webs
- [x] Albaret Earldom/St Justine: lighting has to be fixed in the small room where there is an opening downwards
- [x] Albaret Earldom/St Justine: Lighting needs to be fixed in the room with the crucifixes
- [x] Albaret Earldom/St Justine: lighting needs to be fixed in the room to the right of the crucifixes, which has a giant spider
- [x] Albaret Earldom/St Justine: lighting needs to be fixed in room with webs and moving spike traps
- [x] Albaret Earldom/St Justine: lighting has to be fixed in the room at the bottom, after going down the rope
- [x] Albaret Earldom/Delbasse City: lighting needs to be fixed in the small corridor and in the spiritual section room
- [x] Castle vending machine: should have transparency on its glass case
- [x] Altar: lighting has to be fixed at the bottom
- [x] La tourvelle earldom: waterfall transparency has to be increased
- [x] La tourvelle earldom: the small running waters have to increase the transparency
- [x]  Castle of Eternal Night/Entrance Hall: lighting has to be fixed in the room to the right of the teleporter
- [x]  Castle of Eternal Night/chamber of illusions: lighting has to be fixed in the illusionist's room
- [x]  Castle of Eternal Night/Princely rooms: lighting has to be fixed in the area to the right of the "choose your death" room
